# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f033f968cbc34353f0f83c62a4288f496064f3a6b5a52f28aaf63b119d54f43648f4fe8d40c7f2843d315ae124dbefda294732bc89b328d59ec5ae4407c1938c

test:
  secret_key_base: 2d9fd84fbe3c91dcb50e575b3ec1b8fed87283f8cf3fe969cbd2e679366c4ac37459d6ff739f8da9629b0be2d323221add3a038564e2d27f1cd9793c2ea7e9d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
